### ISSUE TITLE
Supported thonny versions

### ISSUE THREAD

**Issue by BorysekOndrej** [GiraffeReversed/thonny-edulint#3]
Ubuntu 22.04 apt distributes Thonny 3.3.14, which is currently unsupported. We're relying on `from thonny.common import STRING_PSEUDO_FILENAME` which only exists since [4.0.0](https://github.com/thonny/thonny/commit/c731f0dddcebe4e6d377f5524610fb8e5e06fafa#diff-b691868c9a3eb527750f9cfeacc3d6c2371e87e79f83ec89dfb4a69a73b3d08cR17
). Currently we declare support for thonny `>=3.0.0` in [requirements.txt](https://github.com/GiraffeReversed/thonny-edulint/blob/main/requirements.txt).

Ubuntu users can install using `snap install thonny` instead, that gives them much newer version (`4.1.2`).

---

Tracelog on thonny start:

```python
INFO    thonny: Thonny version: 3.3.14
ERROR:root:Failed loading plugin 'thonnycontrib.edulint'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 395, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/noone/.local/lib/python3.10/site-packages/thonnycontrib/edulint/__init__.py", line 15, in <module>
    from thonnycontrib.edulint.view import EduLintView, SubprocessProgramAnalyzer, add_program_analyzer
  File "/home/noone/.local/lib/python3.10/site-packages/thonnycontrib/edulint/view.py", line 10, in <module>
    from thonny.common import STRING_PSEUDO_FILENAME, ToplevelResponse, read_source
ImportError: cannot import name 'STRING_PSEUDO_FILENAME' from 'thonny.common' (/usr/lib/python3/dist-packages/thonny/common.py)
```

---

We will also have to start preparing for Thonny 5.0.0, I've seen references to it already on thonny's master (but not yet released).

**Comment by BorysekOndrej** [comment]
We removed the dependency on `STRING_PSEUDO_FILENAME`, but introduced dependency on `get_front_interpreter_for_subprocess` which was also introduced in `4.0`. So now we've explicitly declared Thonny 4.x as our dependency.

As a result, thonny installed using `apt install thonny` on `Ubuntu22.04` is still unsuported (as of thonny-edulint 0.6.4).

On `Ubuntu24.04` Thonny installed using apt works. Thonny installed using pip works on any system.
