### ISSUE TITLE
Error with linting in new edulint versions (JSON change `edulint_result["configs"][0][0][0]`) 

### ISSUE THREAD

**Issue by BorysekOndrej** [GiraffeReversed/thonny-edulint#5]
An user from MU reported that linting from Thonny with the current version of EduLint doesn't work. 

```python
Traceback (most recent call last):
  File "C:\Users\ondre\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\ondre\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\ondre\AppData\Local\Programs\Thonny\lib\site-packages\thonny\ui_utils.py", line 2297, in poll
    on_completion(proc, out_lines, err_lines)
  File "C:\Users\ondre\AppData\Roaming\Thonny\plugins\Python310\site-packages\thonnycontrib\edulint\__init__.py", line 68, in _parse_and_output_warnings
    if len(edulint_result["configs"]) != 1 or edulint_result["configs"][0][0][0] != main_file_path:
KeyError: 0
```

Edulint 3.4.x worked. For EduLint 3.5.x JSON output is not working at all.  In EduLint 3.6 the JSON output format changed slightly.

<details>
  <summary>Examples of JSON outputs</summary>

EduLint 3.4 JSON output

```json
{
    "configs": [
        [
            [
                "thonnytest.py"
            ],
            {
                "config-file": "default",
                "pylint": [
                    "--load-plugins=edulint.linting.checkers.basic_checker,edulint.linting.checkers.short_problems,edulint.linting.checkers.improper_loop,edulint.linting.checkers.simplifiable_if,edulint.linting.checkers.python_ta_checkers,edulint.linting.checkers.duplication_checker",
                    "--disable=all",
                    "--good-names=_",
                    "--enable=comparison-with-itself,dangerous-default-value,function-redefined,import-outside-toplevel,no-else-break,no-else-return,no-method-argument,no-self-argument,non-ascii-name,not-in-loop,pointless-statement,redefined-argument-from-local,redefined-builtin,return-in-init,self-assigning-variable,trailing-comma-tuple,unnecessary-dict-index-lookup,unnecessary-pass,unneeded-not,unreachable,used-before-assignment,disallowed-name,wildcard-import,simplifiable-if-return,simplifiable-if-assignment,simplifiable-if-expr,simplifiable-if-pass,no-value-in-one-branch-return,no-while-true,use-tighter-boundaries,modifying-iterated-structure,changing-control-variable,use-for-loop,no-global-variables,use-integral-division,use-isdecimal,no-loop-else,at-most-one-iteration-for-loop,redundant-arithmetic,do-not-multiply-mutable,redundant-elif,unreachable-else,invalid-name,consider-using-from-import,reimported,invalid-for-target,one-iteration,no-is-bool,use-ord-letter,use-literal-letter,use-foreach,use-append,use-augmented-assign"
                ],
                "flake8": [
                    "--ignore=F,E,W,C",
                    "--select=W293,W292,E302,E303,E501,F401,W291,E231,F841,E225,E265,E305,E211,E999,E117,E203,F821,E301,E111,E112,E741,E261,E712,E228,W391,E128,E221,E202,E271,E711,E222,E127,E262,E115,E125,E502,E201,W191,E701,E101,E114,E113,E116,E266,E272,E129,E703,E713,E902,E122,F403,F811,E227,E402,F405,E251,E306,E722,E131,E124,E252,F541,F601,F632,F823,E223,E224,E273,E274,E275,E304,E401,E702,E714,E721,E731,E742,E743,E901,F402,F404,F406,F407,F501,F502,F503,F504,F505,F506,F507,F508,F509,F521,F522,F523,F524,F525,F602,F621,F622,F631,F633,F634,F701,F702,F703,F704,F705,F706,F707,F721,F722,F723,F822,F831,F901,W601,W602,W603,W604,W606"
                ],
                "allowed-onechar-names": null,
                "disallowed-builtin-names": [],
                "no-flake8": false,
                "ignore-infile-config-for": [],
                "export-groups": [
                    "python-specific",
                    "enhancement",
                    "complexity"
                ],
                "set-groups": []
            }
        ]
    ],
    "problems": []
}
```

EduLint 3.6 JSON output

```json
{
    "configs": [
        {
            "config-file": "default",
            "pylint": [
                "--load-plugins=edulint.linting.checkers.basic_checker,edulint.linting.checkers.short_problems,edulint.linting.checkers.improper_loop,edulint.linting.checkers.simplifiable_if,edulint.linting.checkers.python_ta_checkers,edulint.linting.checkers.duplication_checker",
                "--disable=all",
                "--good-names=_",
                "--enable=comparison-with-itself,dangerous-default-value,function-redefined,import-outside-toplevel,no-else-break,no-else-return,no-method-argument,no-self-argument,non-ascii-name,not-in-loop,pointless-statement,redefined-argument-from-local,redefined-builtin,return-in-init,self-assigning-variable,trailing-comma-tuple,unnecessary-dict-index-lookup,unnecessary-pass,unneeded-not,unreachable,used-before-assignment,disallowed-name,wildcard-import,simplifiable-if-return,simplifiable-if-assignment,simplifiable-if-expr,simplifiable-if-pass,no-value-in-one-branch-return,no-while-true,use-tighter-boundaries,modifying-iterated-structure,changing-control-variable,use-for-loop,no-global-variables,use-integral-division,use-isdecimal,no-loop-else,at-most-one-iteration-for-loop,redundant-arithmetic,do-not-multiply-mutable,redundant-elif,unreachable-else,invalid-name,consider-using-from-import,reimported,invalid-for-target,one-iteration,no-is-bool,use-ord-letter,use-literal-letter,use-foreach,use-append,use-augmented-assign"
            ],
            "flake8": [
                "--ignore=F,E,W,C",
                "--select=W293,W292,E302,E303,E501,F401,W291,E231,F841,E225,E265,E305,E211,E999,E117,E203,F821,E301,E111,E112,E741,E261,E712,E228,W391,E128,E221,E202,E271,E711,E222,E127,E262,E115,E125,E502,E201,W191,E701,E101,E114,E113,E116,E266,E272,E129,E703,E713,E902,E122,F403,F811,E227,E402,F405,E251,E306,E722,E131,E124,E252,F541,F601,F632,F823,E223,E224,E273,E274,E275,E304,E401,E702,E714,E721,E731,E742,E743,E901,F402,F404,F406,F407,F501,F502,F503,F504,F505,F506,F507,F508,F509,F521,F522,F523,F524,F525,F602,F621,F622,F631,F633,F634,F701,F702,F703,F704,F705,F706,F707,F721,F722,F723,F822,F831,F901,W601,W602,W603,W604,W606"
            ],
            "allowed-onechar-names": null,
            "disallowed-builtin-names": [],
            "no-flake8": false,
            "ignore-infile-config-for": [],
            "export-groups": [
                "python-specific",
                "enhancement",
                "complexity"
            ],
            "set-groups": [],
            "language-file": null
        }
    ],
    "problems": []
}
```

</details>

**Comment by BorysekOndrej** [comment]
Fixed in thonny-edulint 0.6.0.
